# Generated by Django 5.0 on 2023-12-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('blurb', models.TextField()),
                ('images', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('stats', models.JSONField()),
            ],
        ),
    ]
