# Generated by Django 5.0 on 2023-12-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0004_champion_search_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200)),
            ],
        ),
    ]
