# Generated by Django 5.0 on 2024-01-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0006_championdetail_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('plaintext', models.TextField(null=True)),
                ('image', models.CharField(max_length=200)),
                ('gold', models.JSONField(null=True)),
                ('tags', models.TextField(null=True)),
                ('stats', models.JSONField(null=True)),
                ('maps', models.JSONField(null=True)),
                ('depth', models.IntegerField(null=True)),
                ('into_item', models.TextField(null=True)),
                ('from_item', models.TextField(null=True)),
                ('in_store', models.BooleanField(null=True)),
                ('consumed', models.BooleanField(null=True)),
                ('special_recipe', models.IntegerField(null=True)),
                ('required_Ally', models.CharField(max_length=200, null=True)),
                ('required_Champion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.IntegerField()),
                ('map_name', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.IntegerField()),
                ('map', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='championdetail',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
