# Generated by Django 5.0 on 2024-03-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0011_lphistory_updatedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lphistory',
            old_name='updateDate',
            new_name='update_on',
        ),
    ]
