# Generated by Django 5.0 on 2024-03-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0012_rename_updatedate_lphistory_update_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lphistory',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
