# Generated by Django 5.0 on 2024-03-12 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0013_alter_lphistory_update_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lphistory',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
