# Generated by Django 5.0 on 2023-12-23 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='stats',
        ),
        migrations.AddField(
            model_name='champion',
            name='partype',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.CreateModel(
            name='ChampionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skins', models.JSONField()),
                ('lore', models.TextField()),
                ('allytips', models.JSONField()),
                ('enemytips', models.JSONField()),
                ('partype', models.CharField(max_length=200)),
                ('stats', models.JSONField()),
                ('spells', models.JSONField()),
                ('passive', models.JSONField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol_website.champion')),
            ],
        ),
    ]
