# Generated by Django 5.0 on 2023-12-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0002_remove_champion_stats_champion_partype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChampionDetails',
            new_name='ChampionDetail',
        ),
    ]
