# Generated by Django 5.0 on 2024-01-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0005_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='championdetail',
            name='tags',
            field=models.JSONField(default='null'),
        ),
    ]
