# Generated by Django 5.0 on 2024-01-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0007_gamemode_item_map_queue_alter_championdetail_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
