# Generated by Django 5.0 on 2024-01-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0008_alter_queue_description_alter_queue_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
