# Generated by Django 5.0 on 2024-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0009_item_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueType', models.CharField(max_length=200)),
                ('tier', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
                ('summonerName', models.CharField(max_length=200)),
                ('leaguePoints', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
    ]
